### ISSUE TITLE
Support jpz files in Mechapuzzle

### ISSUE THREAD

**Issue by jpd236** [boisvert42/mechapuzzle#13]
I'd send along a pull request, but I'm not sure how you'd prefer to handle it (copying the existing jpz support code here, or referencing another copy from elsewhere?). But I'd find it handy since I tend to use the jpz files to avoid the locked solution grid.

**Comment by horwitz** [comment]
where is the existing JPZ support code (and how much code is there)?

**Comment by boisvert42** [comment]
I was planning on simply leveraging this https://github.com/crosswordnexus/crossword-tools/tree/main/jscrossword
I think I would need to change that a bit if we wanted to maintain puz support though (as I don't believe I read in the solution currently)

**Comment by boisvert42** [comment]
Resolved with https://github.com/boisvert42/mechapuzzle/pull/14
